//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCreation
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectInitials { get; set; }
        public string ProjectManager { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
